name: MyMaid
main: xyz.jaoafa.mymaid.MyMaid
version: 0.0.1
description: General Plugin
database: true
author: mine_book000
softdepend: [EEWAlert, PermissionsEx, WorldEdit, LunaChat, CoreProtect, Votifier, MCBans, DiscordMC]
website: https://jaoafa.com/
commands:
   jf:
      description: Say jaoafa
      usage: /<command>
      permission: mymaid.jf
      permission-message: You do not have permission to perform this command.
   dt:
      description: Teleport to dynmap location.
      usage: /<command> [player] <location>
      permission: mymaid.dt
      permission-message: You do not have permission to perform this command.
   g:
      description: Change your gamemode
      usage: /<command> <0|1|2|3>
      permission: mymaid.gamemode
      permission-message: You do not have permission to perform this command.
   chat:
      description: Make chat with fake player
      usage: /<command> <fake player> <message>
      permission: mymaid.chat
      permission-message: You do not have permission to perform this command.
   iphost:
      description: Find out host name from ip address
      usage: /<command>
      permission: mymaid.iphost
      permission-message: You do not have permission to perform this command.
   data:
      description: Show Server data
      usage: /<command>
      permission: mymaid.data
      permission-message: You do not have permission to perform this command.
   tnt:
      description: TNT Explode is what(philosophical)
      usage: /<command>
      permission: mymaid.tnt
      permission-message: You do not have permission to perform this command.
   afk:
      description: AFK is not AFK
      usage: /<command>
      permission: mymaid.afk
      permission-message: You do not have permission to perform this command.
   j2:
      description: Say jaojao
      usage: /<command>
      permission: mymaid.j2
      permission-message: You do not have permission to perform this command.
   vote:
      description: Console only
      usage: /<command>
      permission: mymaid.vote
      permission-message: You do not have permission to perform this command.
   sign:
      description: Change sentence of sign
      usage: /<command> set <row number> <new message>
      permission: mymaid.sign
      permission-message: You do not have permission to perform this command.
   signlock:
      description: Lock the sign
      usage: /<command>
      permission: mymaid.signlock
      permission-message: You do not have permission to perform this command.
   save-world:
      description: Save the world
      usage: /<command>
      permission: pin_code_auth.save-world
      permission-message: You do not have permission to perform this command.
   head:
      description: Give player skull to you
      usage: /<command> <player>
      permission: mymaid.head
      permission-message: You do not have permission to perform this command.
   cmdb:
      description: Give command block to you
      usage: /<command>
      permission: mymaid.cmdb
      permission-message: You do not have permission to perform this command.
   jail:
      description: Put into eden of south
      usage: |-
             
             /<command> add <player> - Put player into jail
             /<command> remove <player> - Release player from jail
             /<command> list - Show jailer list
      permission: mymaid.jail
      permission-message: You do not have permission to perform this command.
   access:
      description: User Access Data
      usage: /<command> <player>
      permission: mymaid.access
      permission-message: You do not have permission to perform this command.
   ja:
      description: Say jaiuwa
      usage: /<command>
      permission: mymaid.ja
      permission-message: You do not have permission to perform this command.
   cmdsearch:
      description: cmdblock search
      usage: /<command>
      permission: mymaid.cmdsearch
      permission-message: You do not have permission to perform this command.
   skk:
      description: SiKaKu reload
      usage: /<command>
      permission: mymaid.skk
      permission-message: You do not have permission to perform this command.
   makecmd:
      description: Create command makes item
      usage: /<command>
      permission: mymaid.makecmd
      permission-message: You do not have permission to perform this command.
   lag:
      description: Last Lag data
      usage: /<command>
      permission: mymaid.lag
      permission-message: You do not have permission to perform this command.
   mymaid_networkapi:
      description: api(Rcon Only)
      usage: /<command>
      permission: mymaid.lag
      permission-message: You do not have permission to perform this command.
   as:
      description: Arrow Shotter!
      usage: /<command>
      permission: mymaid.as
      permission-message: You do not have permission to perform this command.
   ruleload:
      description: Console Only
      usage: /<command>
      permission: mymaid.ruleload
      permission-message: You do not have permission to perform this command.
   report:
      description: Message Send to Staff.
      usage: /<command>
      permission: mymaid.report
      permission-message: You do not have permission to perform this command.
   explode:
      description: Explode Off OR On
      usage: /<command> X Y Z R
      permission: mymaid.explode
      permission-message: You do not have permission to perform this command.
   e:
      description: Explode Off
      usage: /<command>
      permission: mymaid.e
      permission-message: You do not have permission to perform this command.
   player:
      description: Player Permission
      usage: /<command> [player]
      permission: mymaid.player
      permission-message: You do not have permission to perform this command.
   spawn:
      description: Spawn Teleport
      usage: /<command>
      permission: mymaid.spawn
      permission-message: You do not have permission to perform this command.
   pexup:
      description: Permission Up
      usage: /<command>
      permission: mymaid.pexup
      permission-message: You do not have permission to perform this command.
   pin:
      description: To authenticate the PIN code generated on the Web.
      usage: /<command> [code]
      permission: mymaid.pin
      permission-message: You do not have permission to perform this command.
   inv:
      description: Player Inventory Show
      usage: /<command> [Player]
      permission: mymaid.inv
      permission-message: You do not have permission to perform this command.
   invender:
      description: Player Inventory Enderchest Show
      usage: /<command> [Player]
      permission: mymaid.invender
      permission-message: You do not have permission to perform this command.
   unko:
      description: unko?
      usage: /<command> [Player]
      permission: mymaid.unko
      permission-message: You do not have permission to perform this command.
   guard:
      description: guard
      usage: /<command>
      permission: mymaid.guard
      permission-message: You do not have permission to perform this command.
   invsave:
      description: Inventory Save
      usage: /<command>
      permission: mymaid.invsave
      permission-message: You do not have permission to perform this command.
   invload:
      description: Inventory Load
      usage: /<command>
      permission: mymaid.load
      permission-message: You do not have permission to perform this command.
   var:
      description: Var Set
      usage: /<command>
      permission: mymaid.var
      permission-message: You do not have permission to perform this command.
   varcmd:
      description: VarIn Cmd Run
      usage: /<command>
      permission: mymaid.varcmd
      permission-message: You do not have permission to perform this command.
   ded:
      description: Teleport to ded
      usage: /<command>
      permission: mymaid.ded
      permission-message: You do not have permission to perform this command.
   .:
      description: .
      usage: /<command>
      permission: mymaid.dot
      permission-message: You do not have permission to perform this command.
   dedmsg:
      description: dedmsg
      usage: /<command>
      permission: mymaid.dedmsg
      permission-message: You do not have permission to perform this command.
   dynamic:
      description: dynamic teleport
      usage: /<command>
      permission: mymaid.dynamic
      permission-message: You do not have permission to perform this command.
   where:
      description: where
      usage: /<command>
      permission: mymaid.where
      permission-message: You do not have permission to perform this command.
   eye:
      description: Eye
      usage: /<command>
      permission: mymaid.eye
      permission-message: You do not have permission to perform this command.
   quiz:
      description: Quiz
      usage: /<command>
      permission: mymaid.quiz
      permission-message: You do not have permission to perform this command.
   dc:
      description: Dynmap Compass
      usage: /<command>
      permission: mymaid.dc
      permission-message: You do not have permission to perform this command.
   ck:
      description: ck
      usage: /<command>
      permission: mymaid.ck
      permission-message: You do not have permission to perform this command.
   color:
      description: SKK Color Change
      usage: /<command>
      permission: mymaid.color
      permission-message: You do not have permission to perform this command.
   gettissue:
      description: Get TissueMan
      usage: /<command>
      permission: mymaid.gettissue
      permission-message: You do not have permission to perform this command.
   jao:
      description: jao Point Check
      usage: /<command>
      permission: mymaid.jao
      permission-message: You do not have permission to perform this command.
   mymaid:
      description: MyMaid Config
      usage: /<command>
      permission: mymaid.mymaid
      permission-message: You do not have permission to perform this command.
   discordsend:
      description: discordsend
      usage: /<command>
      permission: mymaid.discordsend
      permission-message: You do not have permission to perform this command.
   upgallery:
      description: Upload Gallery
      usage: /<command>
      permission: mymaid.upgallery
      permission-message: You do not have permission to perform this command.
   home:
      description: Home
      usage: /<command>
      permission: mymaid.home
      permission-message: You do not have permission to perform this command.
   land:
      description: Land
      usage: /<command>
      permission: mymaid.land
      permission-message: You do not have permission to perform this command.
   discordlink:
      description: Discord Account Connect to Minecraft Account.
      usage: /<command>
      permission: mymaid.discordlink
      permission-message: You do not have permission to perform this command.
   wt:
      description: World Teleport
      usage: /<command>
      permission: mymaid.wt
      permission-message: You do not have permission to perform this command.
   myblock:
      description: My Block
      usage: /<command>
      permission: mymaid.myblock
      permission-message: You do not have permission to perform this command.
   mymob:
      description: My Mob
      usage: /<command>
      permission: mymaid.mymob
      permission-message: You do not have permission to perform this command.
   autoheal:
      description: Auto Respawn
      usage: /<command>
      permission: mymaid.autoheal
      permission-message: You do not have permission to perform this command.
   wo:
      description: WO.
      usage: /<command>
      permission: mymaid.wo
      permission-message: You do not have permission to perform this command.
   messenger:
      description: Auto Message Messenger
      usage: /<command>
      permission: mymaid.messenger
      permission-message: You do not have permission to perform this command.
